// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usgducuowlhfkdbatfik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzZ2R1Y3Vvd2xoZmtkYmF0ZmlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNzA0MTQsImV4cCI6MjA2MDc0NjQxNH0.fWbpZ0COHO0l8PMYHIbUuDmPUUuIsZtNPUb17MCfWHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);